CONNECT SYSTEM/MANAGER AS SYSDBA;

-- Crear usuario propietario PFIRMAMG
---------------------------------------
CREATE USER PFIRMAMG IDENTIFIED BY "orecleForSign876"
DEFAULT TABLESPACE "TS_PFIRMA_DATOS"
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TS_PFIRMA_INDICES
QUOTA UNLIMITED ON TS_PFIRMA_DATOS
QUOTA UNLIMITED ON TS_PFIRMA_BLOB
ACCOUNT UNLOCK;

-- Permisos usuario PFIRMAMG
------------------------------
GRANT CREATE SESSION, ALTER SESSION, ALTER USER TO PFIRMAMG;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE TO PFIRMAMG;
GRANT CREATE VIEW TO PFIRMAMG;
GRANT "RESOURCE" TO "PFIRMAMG";
GRANT "CONNECT" TO "PFIRMAMG";
GRANT CREATE TYPE TO PFIRMAMG;

-- Crear usuario de aplicación PFIRMAWEB
-- ---------------------------------------
CREATE USER PFIRMAWEB IDENTIFIED BY "PFIRMAWEB"
DEFAULT TABLESPACE "TS_PFIRMA_DATOS"
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

GRANT CREATE SESSION, ALTER SESSION, ALTER USER TO PFIRMAWEB;
GRANT CREATE SYNONYM TO PFIRMAWEB;
GRANT "RESOURCE" TO "PFIRMAWEB";
GRANT "CONNECT" TO "PFIRMAWEB";

COMMIT;
