CONNECT / AS SYSDBA

-- Crear database
-- ---------------

-- STARTUP NOMOUNT
CREATE TABLESPACE "IPFIRMAMGHIST" DATAFILE '/export/home/app/oradata/pfirma/IPFIRMAMGHIST_000001.ora' SIZE 16M AUTOEXTEND ON;
CREATE TABLESPACE "TPFIRMAMGHIST" DATAFILE '/export/home/app/oradata/pfirma/TPFIRMAMGHIST_000001.ora' SIZE 64M AUTOEXTEND ON;
CREATE TABLESPACE "TPFIRMAMGHISTLOB" DATAFILE '/export/home/app/oradata/pfirma/TPFIRMAMGHISTLOB_000001.ora' SIZE 128M AUTOEXTEND ON;
