-- Crear usuario propietario PFIRMAMGHIST
---------------------------------------
CREATE USER PFIRMAMGHIST IDENTIFIED BY "PFIRMAMGHIST"
DEFAULT TABLESPACE "TPFIRMAMGHIST"
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON IPFIRMAMGHIST
QUOTA UNLIMITED ON TPFIRMAMGHIST
QUOTA UNLIMITED ON TPFIRMAMGHISTLOB
ACCOUNT UNLOCK;

-- Permisos usuario PFIRMAMGHIST
------------------------------
GRANT CREATE SESSION, ALTER SESSION, ALTER USER TO PFIRMAMGHIST;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE TO PFIRMAMGHIST;
GRANT "RESOURCE" TO "PFIRMAMGHIST";
GRANT "CONNECT" TO "PFIRMAMGHIST";

CONNECT SYSTEM/MANAGER AS SYSDBA;
GRANT CREATE TYPE TO PFIRMAMGHIST;

-- Crear usuario de aplicación PFIRMAWEBHIST
-- ---------------------------------------
CREATE USER PFIRMAWEBHIST IDENTIFIED BY "PFIRMAWEBHIST"
DEFAULT TABLESPACE "TPFIRMAMGHIST"
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

GRANT CREATE SESSION, ALTER SESSION, ALTER USER TO PFIRMAWEBHIST;
GRANT CREATE SYNONYM TO PFIRMAWEBHIST;

GRANT "RESOURCE" TO "PFIRMAWEBHIST";
GRANT "CONNECT" TO "PFIRMAWEBHIST";

COMMIT;
