--  CONECTAR CON EL USUARIO DE HISTORICO CREADO

--  Create Tables 
CREATE TABLE PF_ACCIONES
(
	X_ACCION         NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO     VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO     DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	T_ACCION         VARCHAR2(4000 CHAR) NOT NULL,    --  Accion a ejecutar 
	C_TIPO           VARCHAR2(10 CHAR) DEFAULT 'PLSQL' NOT NULL,    --  Tipo de accion ('PLSQL','WEB') 
	DOC_X_DOCUMENTO  NUMBER(10),    --  Clave ajena a PF_DOCUMENTOS 
	PET_X_PETICION   NUMBER(10),    --  Clave ajena a PF_PETICIONES 
	ETIQ_X_ETIQUETA  NUMBER(10) NOT NULL    --  Clave ajena a PF_ETIQUETAS 
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_ACCIONES IS 'Acciones asociadas a documentos y estados'
;
COMMENT ON COLUMN PF_ACCIONES.X_ACCION         IS 'Clave primaria'
;
COMMENT ON COLUMN PF_ACCIONES.C_CREADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ACCIONES.F_CREADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ACCIONES.C_MODIFICADO     IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ACCIONES.F_MODIFICADO     IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ACCIONES.T_ACCION         IS 'Accion a ejecutar'
;
COMMENT ON COLUMN PF_ACCIONES.C_TIPO           IS 'Tipo de accion (''PLSQL'',''WEB'')'
;
COMMENT ON COLUMN PF_ACCIONES.DOC_X_DOCUMENTO  IS 'Clave ajena a PF_DOCUMENTOS'
;
COMMENT ON COLUMN PF_ACCIONES.PET_X_PETICION   IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_ACCIONES.ETIQ_X_ETIQUETA  IS 'Clave ajena a PF_ETIQUETAS'
;

CREATE TABLE PF_APLICACIONES
(
	X_APLICACION         NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_APLICACION         VARCHAR2(120 CHAR) NOT NULL,    --  Codigo de aplicacion 
	D_APLICACION         VARCHAR2(255 CHAR),    --  Descripcion de aplicacion	
	APL_X_APLICACION     NUMBER(10),    --  Clave ajena a PF_APLICACIONES 
	CON_X_CONFIGURACION  NUMBER(10) NOT NULL    --  Clave ajena a PF_CONFIGURACIONES 
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON COLUMN PF_APLICACIONES.X_APLICACION         IS 'Clave primaria'
;
COMMENT ON COLUMN PF_APLICACIONES.C_CREADO             IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_APLICACIONES.F_CREADO             IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_APLICACIONES.C_MODIFICADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_APLICACIONES.F_MODIFICADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_APLICACIONES.C_APLICACION         IS 'Codigo de aplicacion'
;
COMMENT ON COLUMN PF_APLICACIONES.D_APLICACION         IS 'Descripcion de aplicacion'
;
COMMENT ON COLUMN PF_APLICACIONES.APL_X_APLICACION     IS 'Clave ajena a PF_APLICACIONES'
;
COMMENT ON COLUMN PF_APLICACIONES.CON_X_CONFIGURACION  IS 'Clave ajena a PF_CONFIGURACIONES'
;

CREATE TABLE PF_ARCHIVOS
(
	X_ARCHIVO      NUMBER(10) NOT NULL,    -- Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_HASH         VARCHAR2(512) NOT NULL,    -- Identificador unico de archivo 
	C_HASH_ALG     VARCHAR2(10 CHAR) NOT NULL,    -- Algoritmo de generacion del hash 
	C_TIPO         VARCHAR2(10 CHAR) NOT NULL,    -- Tipo de almacenamiento 
	C_URI          VARCHAR2(1000 CHAR),    -- Identificador de almacenamiento 
	B_ARCHIVO      BLOB,    -- Binario del fichero 
	T_COMENTARIOS  VARCHAR2(1000 CHAR),    -- Comentarios adicionales al fichero 
	ARC_X_ARCHIVO  NUMBER(10)    -- Clave ajena a PF_ARCHIVOS 
)
TABLESPACE  TPFIRMAMGHIST
LOB (B_ARCHIVO) STORE AS (TABLESPACE TPFIRMAMGHISTLOB)
;

COMMENT ON TABLE PF_ARCHIVOS IS 'Archivos'
;
COMMENT ON COLUMN PF_ARCHIVOS.X_ARCHIVO      IS 'Clave primaria'
;
COMMENT ON COLUMN PF_ARCHIVOS.C_CREADO       IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ARCHIVOS.F_CREADO       IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ARCHIVOS.C_MODIFICADO   IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ARCHIVOS.F_MODIFICADO   IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ARCHIVOS.C_HASH         IS 'Identificador unico de archivo'
;
COMMENT ON COLUMN PF_ARCHIVOS.C_HASH_ALG     IS 'Algoritmo de generacion del hash'
;
COMMENT ON COLUMN PF_ARCHIVOS.C_TIPO         IS 'Tipo de almacenamiento'
;
COMMENT ON COLUMN PF_ARCHIVOS.C_URI          IS 'Identificador de almacenamiento'
;
COMMENT ON COLUMN PF_ARCHIVOS.B_ARCHIVO      IS 'Binario del fichero'
;
COMMENT ON COLUMN PF_ARCHIVOS.T_COMENTARIOS  IS 'Comentarios adicionales al fichero'
;
COMMENT ON COLUMN PF_ARCHIVOS.ARC_X_ARCHIVO  IS 'Clave ajena a PF_ARCHIVOS'
;

CREATE TABLE PF_COMENTARIOS
(
	X_COMENTARIO    NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	D_ASUNTO        VARCHAR2(255 CHAR) NOT NULL,    --  Asunto o titulo del comentario 
	T_COMENTARIO    VARCHAR2(1000 CHAR) NOT NULL,    --  Texto del comentario 
	PET_X_PETICION  NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES 
	USU_X_USUARIO   NUMBER(10) NOT NULL    --  Clave ajena a PF_USUARIOS 
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_COMENTARIOS IS 'Comentarios a las peticiones'
;
COMMENT ON COLUMN PF_COMENTARIOS.X_COMENTARIO    IS 'Clave primaria'
;
COMMENT ON COLUMN PF_COMENTARIOS.C_CREADO        IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_COMENTARIOS.F_CREADO        IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_COMENTARIOS.C_MODIFICADO    IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_COMENTARIOS.F_MODIFICADO    IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_COMENTARIOS.D_ASUNTO        IS 'Asunto o titulo del comentario'
;
COMMENT ON COLUMN PF_COMENTARIOS.T_COMENTARIO    IS 'Texto del comentario'
;
COMMENT ON COLUMN PF_COMENTARIOS.PET_X_PETICION  IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_COMENTARIOS.USU_X_USUARIO   IS 'Clave ajena a PF_USUARIOS'
;

CREATE TABLE PF_DOCUMENTOS
(
	X_DOCUMENTO            NUMBER(10) NOT NULL,    -- Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_HASH                 VARCHAR2(10) NOT NULL,    -- Identificador del documento 
	D_NOMBRE               VARCHAR2(255 CHAR) NOT NULL,    -- Nombre del documento 
	D_MIME                 VARCHAR2(255 CHAR) DEFAULT 'application/octet-stream' NOT NULL,    -- Tipo mime del documento 
	T_COMENTARIOS          VARCHAR2(1000 CHAR),    -- Comentarios 
	L_FIRMABLE             VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,    -- Indica si el documento es firmable o no 
	C_PREFIRMA             VARCHAR2(100 CHAR),    -- Identificador de documento obtenido por prefirma 
	PET_X_PETICION         NUMBER(10) NOT NULL,    -- Clave ajena a PF_PETICIONES 
	TDOC_X_TIPO_DOCUMENTO  NUMBER(10) NOT NULL,    -- Clave ajena a PF_TIPOS_DOCUMENTO 
	ARC_X_ARCHIVO          NUMBER(10) NOT NULL,    -- Clave ajena a PF_ARCHIVOS
	AMB_X_AMBITO           NUMBER(10) DEFAULT 1 NOT NULL,    -- Clave ajena a PF_AMBITOS_DOCUMENTOS 
	L_ES_FIRMA			   VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,-- Indica si el documento en sÃ­ es una firma.
	C_COMENTARIO_ANEXO VARCHAR2(50 CHAR)
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON COLUMN PF_DOCUMENTOS.X_DOCUMENTO            IS 'Clave primaria'
;
COMMENT ON COLUMN PF_DOCUMENTOS.C_CREADO               IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_DOCUMENTOS.F_CREADO               IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_DOCUMENTOS.C_MODIFICADO           IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_DOCUMENTOS.F_MODIFICADO           IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_DOCUMENTOS.C_HASH                 IS 'Identificador del documento'
;
COMMENT ON COLUMN PF_DOCUMENTOS.D_NOMBRE               IS 'Nombre del documento'
;
COMMENT ON COLUMN PF_DOCUMENTOS.D_MIME                 IS 'Tipo mime del documento'
;
COMMENT ON COLUMN PF_DOCUMENTOS.T_COMENTARIOS          IS 'Comentarios'
;
COMMENT ON COLUMN PF_DOCUMENTOS.L_FIRMABLE             IS 'Indica si el documento es firmable o no'
;
COMMENT ON COLUMN PF_DOCUMENTOS.C_PREFIRMA             IS 'Identificador de documento obtenido por prefirma'
;
COMMENT ON COLUMN PF_DOCUMENTOS.PET_X_PETICION         IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_DOCUMENTOS.TDOC_X_TIPO_DOCUMENTO  IS 'Clave ajena a PF_TIPOS_DOCUMENTO'
;
COMMENT ON COLUMN PF_DOCUMENTOS.ARC_X_ARCHIVO          IS 'Clave ajena a PF_ARCHIVOS'
;
COMMENT ON COLUMN PF_DOCUMENTOS.AMB_X_AMBITO 		   IS 'Clave ajena a PF_AMBITOS_DOCUMENTOS'
;
COMMENT ON COLUMN PF_DOCUMENTOS.L_ES_FIRMA  		   IS 'Indica si el documento en sí es una firma'
;
COMMENT ON COLUMN PF_DOCUMENTOS.C_COMENTARIO_ANEXO IS 'Indica el comentario para el nuevo anexo'
;

CREATE TABLE PF_ETIQUETAS_PETICION
(
	X_ETIQUETA_PETICION  NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	PET_X_PETICION       NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES 
	USU_X_USUARIO        NUMBER(10),    --  Clave ajena a PF_USUARIOS 
	ETIQ_X_ETIQUETA      NUMBER(10) NOT NULL,    --  Clave ajena a PF_ETIQUETAS
	LFIR_X_LINEA_FIRMA 	 NUMBER(10), 			-- Clave ajena a PF_LINEAS_FIRMA
	C_HASH 				 VARCHAR2(10) -- Hash de etiqueta petición
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON COLUMN PF_ETIQUETAS_PETICION.X_ETIQUETA_PETICION  IS 'Clave primaria'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.C_CREADO             IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.F_CREADO             IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.C_MODIFICADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.F_MODIFICADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.PET_X_PETICION       IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.USU_X_USUARIO        IS 'Clave ajena a PF_USUARIOS'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.ETIQ_X_ETIQUETA      IS 'Clave ajena a PF_ETIQUETAS'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.LFIR_X_LINEA_FIRMA   IS 'Clave ajena a PF_LINEAS_FIRMA'
;
COMMENT ON COLUMN PF_ETIQUETAS_PETICION.C_HASH   IS 'Código hash de la etiqueta petición'
;

CREATE TABLE PF_FIRMANTES
(
	X_FIRMANTE                  NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	USU_X_USUARIO               NUMBER(10) NOT NULL,    --  Clave ajena a PF_USUARIOS 
	LFIR_X_LINEA_FIRMA          NUMBER(10) NOT NULL,    --  Clave ajena a PF_LINEAS_FIRMA 
	FIR_X_FIRMANTE              NUMBER(10),    --  Clave ajena a PF_FIRMANTES 
	FAUT_X_FILTRO_AUTORIZACION  NUMBER(10)    --  Clave ajena a PF_FILTROS_ATURORIZACION 
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_FIRMANTES IS 'Tabla de firmantes'
;
COMMENT ON COLUMN PF_FIRMANTES.X_FIRMANTE                  IS 'Clave primaria'
;
COMMENT ON COLUMN PF_FIRMANTES.C_CREADO                    IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMANTES.F_CREADO                    IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMANTES.C_MODIFICADO                IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMANTES.F_MODIFICADO                IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMANTES.USU_X_USUARIO               IS 'Clave ajena a PF_USUARIOS'
;
COMMENT ON COLUMN PF_FIRMANTES.LFIR_X_LINEA_FIRMA          IS 'Clave ajena a PF_LINEAS_FIRMA'
;
COMMENT ON COLUMN PF_FIRMANTES.FIR_X_FIRMANTE              IS 'Clave ajena a PF_FIRMANTES'
;
COMMENT ON COLUMN PF_FIRMANTES.FAUT_X_FILTRO_AUTORIZACION  IS 'Clave ajena a PF_FILTROS_ATURORIZACION'
;

CREATE TABLE PF_FIRMAS
(
	X_FIRMA          NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	F_ESTADO         DATE NOT NULL,    --  Fecha desde la que se encuentra en dicho estado 
	T_OBSERVACIONES  VARCHAR2(1000 CHAR),    --  Observaciones 
	C_TRANSACCION    VARCHAR2(255 CHAR),    --  Identificador de transaccion 
	C_APLICACION     VARCHAR2(255 CHAR),    --  Identificador de aplicacion 
	C_SERVIDOR       VARCHAR2(255 CHAR),    --  Identificador de servidor 
	C_TIPO           VARCHAR2(10 CHAR) DEFAULT 'ID' NOT NULL,    -- Tipo de almacenamiento de la firma 
	C_URI            VARCHAR2(1000 CHAR),    -- Identificador de almacenamiento de la firma 
	B_FIRMA          BLOB,    -- Binario de firma 	
	C_FORMATO		 VARCHAR2(30 CHAR) DEFAULT 'CMS' NOT NULL, -- formato de firma	
	DOC_X_DOCUMENTO  NUMBER(10) NOT NULL,    -- Clave ajena a PF_DOCUMENTOS 
	FIR_X_FIRMANTE   NUMBER(10) NOT NULL,    -- Clave ajena a PF_FIRMANTES 
	USU_X_USUARIO    NUMBER(10) NOT NULL,     -- Clave ajena a PF_USUARIOS
	CSV				 VARCHAR2(32 CHAR),            -- Código seguro de verificaciÃ³n de la firma
	B_INFORME		 BLOB, 					 -- Binario del informe de firma
	F_VALIDO		 DATE    --  Fecha de validez del cetificado que ha realizado la firma 
)
TABLESPACE  TPFIRMAMGHIST
LOB (B_FIRMA) STORE AS (TABLESPACE TPFIRMAMGHISTLOB)
LOB (B_INFORME) STORE AS (TABLESPACE TPFIRMAMGHISTLOB)
;

COMMENT ON TABLE PF_FIRMAS IS 'Firmas'
;
COMMENT ON COLUMN PF_FIRMAS.X_FIRMA          IS 'Clave primaria'
;
COMMENT ON COLUMN PF_FIRMAS.C_CREADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMAS.F_CREADO         IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMAS.C_MODIFICADO     IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMAS.F_MODIFICADO     IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_FIRMAS.F_ESTADO         IS 'Fecha desde la que se encuentra en dicho estado'
;
COMMENT ON COLUMN PF_FIRMAS.T_OBSERVACIONES  IS 'Observaciones'
;
COMMENT ON COLUMN PF_FIRMAS.C_TRANSACCION    IS 'Identificador de transaccion'
;
COMMENT ON COLUMN PF_FIRMAS.C_APLICACION     IS 'Identificador de aplicacion'
;
COMMENT ON COLUMN PF_FIRMAS.C_SERVIDOR       IS 'Identificador de servidor'
;
COMMENT ON COLUMN PF_FIRMAS.C_TIPO           IS 'Tipo de almacenamiento de la firma'
;
COMMENT ON COLUMN PF_FIRMAS.C_URI            IS 'Identificador de almacenamiento de la firma'
;
COMMENT ON COLUMN PF_FIRMAS.B_FIRMA          IS 'Binario de firma'
;
COMMENT ON COLUMN PF_FIRMAS.C_FORMATO        IS 'Formato de la firma CMS/XaDES/CaDES'
;
COMMENT ON COLUMN PF_FIRMAS.DOC_X_DOCUMENTO  IS 'Clave ajena a PF_DOCUMENTOS'
;
COMMENT ON COLUMN PF_FIRMAS.FIR_X_FIRMANTE   IS 'Clave ajena a PF_FIRMANTES'
;
COMMENT ON COLUMN PF_FIRMAS.USU_X_USUARIO    IS 'Clave ajena a PF_USUARIOS'
;
COMMENT ON COLUMN PF_FIRMAS.CSV 			 IS 'Código seguro de verificación de la firma'
;

CREATE TABLE PF_LINEAS_FIRMA
(
	X_LINEA_FIRMA   NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria  
	C_TIPO 			VARCHAR2(10 CHAR) DEFAULT 'FIRMA' NOT NULL,    -- Tipo de accion (firma o visto bueno) 	
	PET_X_PETICION  NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES 
	LFIR_X_LINEA_FIRMA  NUMBER(10)    --  Clave ajena a PF_LINEAS_FIRMA
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_LINEAS_FIRMA IS 'Lineas de firma'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.X_LINEA_FIRMA   IS 'Clave primaria'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.C_CREADO        IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.F_CREADO        IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.C_MODIFICADO    IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.F_MODIFICADO    IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.PET_X_PETICION  IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.LFIR_X_LINEA_FIRMA  IS 'Clave ajena a PF_LINEAS_FIRMA'
;
COMMENT ON COLUMN PF_LINEAS_FIRMA.C_TIPO IS 'Tipo de accion (firma o visto bueno)'
;

CREATE TABLE PF_PETICIONES
(
	X_PETICION               NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_HASH                   VARCHAR2(10) NOT NULL,    --  Codigo de la peticion 
	F_ENTRADA                DATE NOT NULL,    --  Fecha de alta de le peticion 
	F_INICIO                 DATE,    --  Fecha de inicio 
	F_CADUCIDAD              DATE,    --  Fecha de caducidad 
	D_REFERENCIA             VARCHAR2(30 CHAR),    --  Referencia de la peticion 
	D_ASUNTO                 VARCHAR2(255 CHAR),    --  Asunto 
	L_FIRMA_EN_CASCADA       VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,    --  Indica si se trata de firma en cascada 
	L_FIRMA_PRIMER_FIRMANTE  VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,    --  Indica si se trata de firma de primer firmante 
	T_PETICION               CLOB,    --  Texto de la peticion 
	APL_X_APLICACION         NUMBER(10) NOT NULL,    -- Clave ajena a PF_APLICACIONES
	NV_IMP_X_IMPORTANCIA	 NUMBER(10) NOT NULL,
	L_SELLO_TIEMPO			 VARCHAR2(1 CHAR) DEFAULT 'X' NOT NULL-- Indica si la peticiÃ³n debe firmarse con sello de tiempo.
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_PETICIONES IS 'Tabla de peticiones'
;
COMMENT ON COLUMN PF_PETICIONES.X_PETICION               IS 'Clave primaria'
;
COMMENT ON COLUMN PF_PETICIONES.C_CREADO                 IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES.F_CREADO                 IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES.C_MODIFICADO             IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES.F_MODIFICADO             IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES.C_HASH                   IS 'Codigo de la peticion'
;
COMMENT ON COLUMN PF_PETICIONES.F_ENTRADA                IS 'Fecha de alta de le peticion'
;
COMMENT ON COLUMN PF_PETICIONES.F_INICIO                 IS 'Fecha de inicio'
;
COMMENT ON COLUMN PF_PETICIONES.F_CADUCIDAD              IS 'Fecha de caducidad'
;
COMMENT ON COLUMN PF_PETICIONES.D_REFERENCIA             IS 'Referencia de la peticion'
;
COMMENT ON COLUMN PF_PETICIONES.D_ASUNTO                 IS 'Asunto'
;
COMMENT ON COLUMN PF_PETICIONES.L_FIRMA_EN_CASCADA       IS 'Indica si se trata de firma en cascada'
;
COMMENT ON COLUMN PF_PETICIONES.L_FIRMA_PRIMER_FIRMANTE  IS 'Indica si se trata de firma de primer firmante'
;
COMMENT ON COLUMN PF_PETICIONES.T_PETICION               IS 'Texto de la peticion'
;
COMMENT ON COLUMN PF_PETICIONES.APL_X_APLICACION         IS 'Clave ajena a PF_APLICACIONES'
;
COMMENT ON COLUMN PF_PETICIONES.L_SELLO_TIEMPO			 IS 'Indica si las firmas de la petición llevarán sello de tiempo o no'
;

CREATE TABLE PF_PETICIONES_AVISO
(
	X_PETICION_AVISO  NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	PET_X_PETICION    NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES 
	ETIQ_X_ETIQUETA   NUMBER(10) NOT NULL    --  Clave ajena a PF_ETIQUETAS 
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_PETICIONES_AVISO IS 'Avisos relacionados con peticiones'
;
COMMENT ON COLUMN PF_PETICIONES_AVISO.X_PETICION_AVISO  IS 'Clave primaria'
;
COMMENT ON COLUMN PF_PETICIONES_AVISO.C_CREADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_AVISO.F_CREADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_AVISO.C_MODIFICADO      IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_AVISO.F_MODIFICADO      IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_AVISO.PET_X_PETICION    IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_PETICIONES_AVISO.ETIQ_X_ETIQUETA   IS 'Clave ajena a PF_ETIQUETAS'
;

CREATE TABLE PF_PETICIONES_HISTORICO
(
	X_PETICION_HISTORICO  NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_PETICION_HISTORICO  VARCHAR2(30 CHAR) NOT NULL,    --  Codigo de texto de historico 
	T_PETICION_HISTORICO  VARCHAR2(1000 CHAR),    --  Descripcion de texto de historico 
	PET_X_PETICION        NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES 
	USU_X_USUARIO         NUMBER(10)    -- Clave ajena a PF_USUARIOS 	
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON COLUMN PF_PETICIONES_HISTORICO.X_PETICION_HISTORICO  IS 'Clave primaria'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.C_CREADO              IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.F_CREADO              IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.C_MODIFICADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.F_MODIFICADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.C_PETICION_HISTORICO  IS 'Codigo de texto de historico'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.T_PETICION_HISTORICO  IS 'Descripcion de texto de historico'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.PET_X_PETICION        IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_PETICIONES_HISTORICO.USU_X_USUARIO         IS 'Clave ajena a PF_USUARIOS'
;

CREATE TABLE PF_PETICIONES_VALOR
(
	X_PETICION_VALOR  NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	T_VALOR           VARCHAR2(1000 CHAR) NOT NULL,    --  Valor de la informacion 
	PEIN_X_PETICION_INFORMACION   NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES_VALOR 
	PET_X_PETICION   NUMBER(10) NOT NULL    --  Clave ajena a PF_PETICIONES 
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON COLUMN PF_PETICIONES_VALOR.X_PETICION_VALOR  IS 'Clave primaria'
;
COMMENT ON COLUMN PF_PETICIONES_VALOR.C_CREADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_VALOR.F_CREADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_VALOR.C_MODIFICADO      IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_VALOR.F_MODIFICADO      IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_PETICIONES_VALOR.T_VALOR           IS 'Valor de la informacion'
;
COMMENT ON COLUMN PF_PETICIONES_VALOR.PEIN_X_PETICION_INFORMACION   IS 'Clave ajena a PF_PETICIONES_VALOR'
;
COMMENT ON COLUMN PF_PETICIONES_VALOR.PET_X_PETICION   IS 'Clave ajena a PF_PETICIONES'
;

CREATE TABLE PF_USUARIOS
(
	X_USUARIO     NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_IDENTIFICADOR         VARCHAR2(30 CHAR) NOT NULL,    --  DNI del usuario o codigo de cargo
	C_ANAGRAMA    VARCHAR2(50 CHAR),    --  Anagrama fiscal largo 
	D_NOMBRE      VARCHAR2(50 CHAR),    --  Nombre del usuario 
	D_APELL1      VARCHAR2(50 CHAR),    --  Primer apellido del usuario 
	D_APELL2      VARCHAR2(50 CHAR),    --  Segundo apellido del usuario 
	L_VIGENTE     VARCHAR2(1 CHAR) DEFAULT 'S',    -- Vigencia de un usuario o cargo 	
	C_TIPO        VARCHAR2(10 CHAR) DEFAULT 'USUARIO' NOT NULL,    -- Campo que distingue entre usuario y cargo
	PROV_X_PROVINCIA     NUMBER(10),						-- Clave ajena a PF_PROVINCIA
	L_VISIBLE 			 VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL, -- Visibilidad de usuario para usuarios de otras sedes
	L_ALERTA_NOTIF		 VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL  -- Habilitar alerta inicial de notificaciones	 	
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_USUARIOS IS 'Usuarios'
;
COMMENT ON COLUMN PF_USUARIOS.X_USUARIO     IS 'Clave primaria'
;
COMMENT ON COLUMN PF_USUARIOS.C_CREADO      IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS.F_CREADO      IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS.C_MODIFICADO  IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS.F_MODIFICADO  IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS.C_IDENTIFICADOR         IS 'DNI del usuario o codigo de cargo'
;
COMMENT ON COLUMN PF_USUARIOS.C_ANAGRAMA    IS 'Anagrama fiscal largo'
;
COMMENT ON COLUMN PF_USUARIOS.D_NOMBRE      IS 'Nombre del usuario'
;
COMMENT ON COLUMN PF_USUARIOS.D_APELL1      IS 'Primer apellido del usuario'
;
COMMENT ON COLUMN PF_USUARIOS.D_APELL2      IS 'Segundo apellido del usuario'
;
COMMENT ON COLUMN PF_USUARIOS.L_VIGENTE        IS 'Vigencia de un usuario o cargo'
;
COMMENT ON COLUMN PF_USUARIOS.C_TIPO           IS 'Campo que distingue entre usuario y cargo'
;
COMMENT ON COLUMN PF_USUARIOS.PROV_X_PROVINCIA 		   IS 'Clave ajena a PF_PROVINCIA'
;
COMMENT ON COLUMN PF_USUARIOS.L_VISIBLE 		   IS 'Visibilidad de un usuario para usuarios de otras sedes'
;
COMMENT ON COLUMN PF_USUARIOS.L_ALERTA_NOTIF IS 'Habilitar alerta inicial de notificaciones'
;

CREATE TABLE PF_USUARIOS_REMITENTE
(
	X_USUARIO_REMITENTE  NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	L_NOTIFICA_EMAIL      VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,    --  Indica si se notifica al remitente via email 
	L_NOTIFICA_MOVIL      VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,    --  Indica si se notifica al remitente via movil 
	USU_X_USUARIO         NUMBER(10) NOT NULL,    --  Clave ajena a PF_USUARIOS 
	PET_X_PETICION        NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES 
	GRU_X_GRUPO NUMBER(10),
	ESTADO_PARA_REMITENTE VARCHAR2(50)
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON TABLE PF_USUARIOS_REMITENTE IS 'Tabla de remitentes de peticiones'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.X_USUARIO_REMITENTE  IS 'Clave primaria'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.C_CREADO              IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.F_CREADO              IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.C_MODIFICADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.F_MODIFICADO          IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.L_NOTIFICA_EMAIL      IS 'Indica si se notifica al remitente via email'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.L_NOTIFICA_MOVIL      IS 'Indica si se notifica al remitente via movil'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.USU_X_USUARIO         IS 'Clave ajena a PF_USUARIOS'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.PET_X_PETICION        IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.GRU_X_GRUPO IS 'Clave ajena a PF_GRUPOS'
;
COMMENT ON COLUMN PF_USUARIOS_REMITENTE.ESTADO_PARA_REMITENTE IS 'Por medio de este campo se identifica en que estado esta para los remitentes, porque los remitentes no cuentan con etiquetas de estado en la peticion'
;

--  Create Primary Key Constraints 
ALTER TABLE PF_ACCIONES ADD CONSTRAINT PF_ACC_PK 
	PRIMARY KEY (X_ACCION) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_APLICACIONES ADD CONSTRAINT PF_APL_PK 
	PRIMARY KEY (X_APLICACION) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_ARCHIVOS ADD CONSTRAINT PF_ARC_PK 
	PRIMARY KEY (X_ARCHIVO) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_COMENTARIOS ADD CONSTRAINT PF_COM_PK 
	PRIMARY KEY (X_COMENTARIO) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_DOCUMENTOS ADD CONSTRAINT PF_DOC_PK 
	PRIMARY KEY (X_DOCUMENTO) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_ETIQUETAS_PETICION ADD CONSTRAINT PF_ETPE_PK 
	PRIMARY KEY (X_ETIQUETA_PETICION) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_FIRMANTES ADD CONSTRAINT PF_FIR_PK 
	PRIMARY KEY (X_FIRMANTE) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_FIRMAS ADD CONSTRAINT PF_FIRM_PK 
	PRIMARY KEY (X_FIRMA) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_LINEAS_FIRMA ADD CONSTRAINT PF_LFIR_PK 
	PRIMARY KEY (X_LINEA_FIRMA) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_PETICIONES ADD CONSTRAINT PF_PET_PK 
	PRIMARY KEY (X_PETICION) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_PETICIONES_AVISO ADD CONSTRAINT PF_PAVI_PK 
	PRIMARY KEY (X_PETICION_AVISO) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_PETICIONES_HISTORICO ADD CONSTRAINT PF_PEHI_PK 
	PRIMARY KEY (X_PETICION_HISTORICO) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_PETICIONES_VALOR ADD CONSTRAINT PF_PEVA_PK 
	PRIMARY KEY (X_PETICION_VALOR) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_USUARIOS ADD CONSTRAINT PF_USU_PK 
	PRIMARY KEY (X_USUARIO) USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_USUARIOS_REMITENTE ADD CONSTRAINT PF_UREM_PK 
	PRIMARY KEY (X_USUARIO_REMITENTE) USING INDEX TABLESPACE IPFIRMAMGHIST
;

--  Create Constraints. Domains.
ALTER TABLE PF_ACCIONES
ADD CONSTRAINT PF_ACC_C_TIPO_CH CHECK (C_TIPO IN ('PLSQL', 'WEB'))
;


ALTER TABLE PF_APLICACIONES
	ADD CONSTRAINT PF_APL_C_APLICACION_UK UNIQUE (C_APLICACION)
	USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_ETIQUETAS_PETICION
	ADD CONSTRAINT PF_HASH_ETPET_UK UNIQUE (C_HASH)
	USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_FIRMAS
	ADD CONSTRAINT PF_CSV_FIRMA_UK UNIQUE (CSV)
	USING INDEX TABLESPACE IPFIRMAMGHIST
;

ALTER TABLE PF_DOCUMENTOS
ADD CONSTRAINT PF_DOC_L_FIRMABLE_CH CHECK (L_FIRMABLE IN ('S','N'))
;

ALTER TABLE PF_PETICIONES
ADD CONSTRAINT PF_PET_L_FIRMA_CASCADA_CH CHECK (L_FIRMA_EN_CASCADA IN ('N', 'S'))
;

ALTER TABLE PF_PETICIONES
ADD CONSTRAINT PF_PET_L_FIRMA_PRIMER_CH CHECK (L_FIRMA_PRIMER_FIRMANTE IN ('S','N'))
;

ALTER TABLE PF_PETICIONES
	ADD CONSTRAINT PF_PET_C_HASH_UK UNIQUE (C_HASH)
;

ALTER TABLE PF_DOCUMENTOS
	ADD CONSTRAINT PF_DOC_C_HASH_UK UNIQUE (C_HASH)
;

ALTER TABLE PF_ARCHIVOS
	ADD CONSTRAINT PF_ARC_C_HASH_UK UNIQUE (C_HASH, C_TIPO)
;

ALTER TABLE PF_USUARIOS
ADD CONSTRAINT PF_USU_L_VIGENTE_CH CHECK (L_VIGENTE IN ('S','N'))
;

--  Create Foreign Key Constraints 

ALTER TABLE PF_ACCIONES ADD CONSTRAINT PF_ACC_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_COMENTARIOS ADD CONSTRAINT PF_COM_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_DOCUMENTOS ADD CONSTRAINT PF_DOC_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_DOCUMENTOS ADD CONSTRAINT PF_DOC_ARC_FK 
	FOREIGN KEY (ARC_X_ARCHIVO) REFERENCES PF_ARCHIVOS (X_ARCHIVO)
;

ALTER TABLE PF_ETIQUETAS_PETICION ADD CONSTRAINT PF_ETPE_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_FIRMANTES ADD CONSTRAINT PF_FIR_USU_FK 
	FOREIGN KEY (USU_X_USUARIO) REFERENCES PF_USUARIOS (X_USUARIO)
;

ALTER TABLE PF_FIRMANTES ADD CONSTRAINT PF_FIR_LFIR_FK 
	FOREIGN KEY (LFIR_X_LINEA_FIRMA) REFERENCES PF_LINEAS_FIRMA (X_LINEA_FIRMA)
;

ALTER TABLE PF_FIRMANTES ADD CONSTRAINT PF_FIR_FIR_FK 
	FOREIGN KEY (FIR_X_FIRMANTE) REFERENCES PF_FIRMANTES (X_FIRMANTE)
;

ALTER TABLE PF_FIRMAS ADD CONSTRAINT PF_FIRM_FIR_FK 
	FOREIGN KEY (FIR_X_FIRMANTE) REFERENCES PF_FIRMANTES (X_FIRMANTE)
;

ALTER TABLE PF_LINEAS_FIRMA ADD CONSTRAINT PF_LFIR_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_LINEAS_FIRMA ADD CONSTRAINT PF_LFIR_LFIR_FK 
	FOREIGN KEY (LFIR_X_LINEA_FIRMA) REFERENCES PF_LINEAS_FIRMA (X_LINEA_FIRMA)
;

ALTER TABLE PF_PETICIONES ADD CONSTRAINT PF_PET_APL_FK 
	FOREIGN KEY (APL_X_APLICACION) REFERENCES PF_APLICACIONES (X_APLICACION)
;

ALTER TABLE PF_PETICIONES_AVISO ADD CONSTRAINT PF_PAVI_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_PETICIONES_VALOR ADD CONSTRAINT PF_PEVA_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_USUARIOS_REMITENTE ADD CONSTRAINT PF_UREM_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

ALTER TABLE PF_ARCHIVOS ADD CONSTRAINT PF_ARC_ARC_FK 
	FOREIGN KEY (ARC_X_ARCHIVO) REFERENCES PF_ARCHIVOS (X_ARCHIVO)
;

ALTER TABLE PF_PETICIONES_HISTORICO ADD CONSTRAINT PF_PEHI_PET_FK 
	FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION)
;

-- Create indexes

CREATE INDEX PF_I_ACC_PET_FK ON PF_ACCIONES
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_APL_APL_FK ON PF_APLICACIONES
(APL_X_APLICACION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_COM_PET_FK ON PF_COMENTARIOS
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_DOC_PET_FK ON PF_DOCUMENTOS
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_DOC_ARC_FK ON PF_DOCUMENTOS
(ARC_X_ARCHIVO ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_ETPE_PET_FK ON PF_ETIQUETAS_PETICION
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_ETPE_HASH_FK ON PF_ETIQUETAS_PETICION
(C_HASH ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_FIR_USU_FK ON PF_FIRMANTES
(USU_X_USUARIO ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_FIR_LFIR_FK ON PF_FIRMANTES
(LFIR_X_LINEA_FIRMA ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_FIR_FIR_FK ON PF_FIRMANTES
(FIR_X_FIRMANTE ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_FIRM_FIR_FK ON PF_FIRMAS
(FIR_X_FIRMANTE ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_FIRM_CSV_FK ON PF_FIRMAS
(CSV ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_FIRM_VALIDO ON PF_FIRMAS
(F_VALIDO)
TABLESPACE IPFIRMAMGHIST 
;

CREATE INDEX PF_I_LFIR_PET_FK ON PF_LINEAS_FIRMA
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_LFIR_LFIR_FK ON PF_LINEAS_FIRMA
(LFIR_X_LINEA_FIRMA ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_PAVI_PET_FK ON PF_PETICIONES_AVISO
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_PEHI_PET_FK ON PF_PETICIONES_HISTORICO
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_PEVA_PET_FK ON PF_PETICIONES_VALOR
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_UREM_PET_FK ON PF_USUARIOS_REMITENTE
(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_UREM_USU_FK ON PF_USUARIOS_REMITENTE
(USU_X_USUARIO ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_ARC_ARC_FK ON PF_ARCHIVOS
(ARC_X_ARCHIVO ASC)
TABLESPACE  IPFIRMAMGHIST
;

CREATE INDEX PF_I_PET_APL_FK ON PF_PETICIONES
(APL_X_APLICACION ASC)
TABLESPACE  IPFIRMAMGHIST
;

------------------------ ACTUALIZACIÓN TABLAS INTERFAZ GENÉRICA ------------------------

-- OBJETOS COMO SISTEMA PORTAFIRMAS

-- TABLA PF_DOCELWEB_SOLICITUD_SPFIRMA

CREATE TABLE PF_DOCELWEB_SOLICITUD_SPFIRMA
    (
        X_ID_TRANSACCION NUMBER(10) NOT NULL,
		C_CREADO VARCHAR2(20) DEFAULT USER NOT NULL,    	--  Campo de auditoria
		F_CREADO DATE DEFAULT SYSDATE NOT NULL,    			--  Campo de auditoria
		C_MODIFICADO VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria
		F_MODIFICADO DATE DEFAULT SYSDATE NOT NULL,    		--  Campo de auditoria              
        D_ESTADO CHAR(1) DEFAULT 'A' NOT NULL,
        D_DESCRIPCION VARCHAR2(255 CHAR),
        D_PRIORIDAD CHAR(1) DEFAULT 'N' NOT NULL,
        D_FORMATO_FIRMA VARCHAR2(5 CHAR) DEFAULT 'CADES' NOT NULL,
        D_VERSION_XADES VARCHAR2(5 CHAR),
        D_TIPO_MULTIFIRMA VARCHAR2(10 CHAR) DEFAULT 'NO' NOT NULL,
        F_FECHA_LIMITE DATE,
        D_REMITENTE VARCHAR2(100 CHAR) NOT NULL,
        SOLICITUD_X_GESTOR NUMBER(10) NOT NULL,
        SOLICITUD_X_PETICION NUMBER(10)
    )
TABLESPACE TPFIRMAMGHIST;
    
ALTER TABLE PF_DOCELWEB_SOLICITUD_SPFIRMA ADD CONSTRAINT PF_DOCELWEB_SOLICITUD_SPFIR_PK 
    PRIMARY KEY (X_ID_TRANSACCION) USING INDEX TABLESPACE IPFIRMAMGHIST;
ALTER TABLE PF_DOCELWEB_SOLICITUD_SPFIRMA ADD CONSTRAINT PF_DOCELWEB_SOL_PET_FK
	FOREIGN KEY (SOLICITUD_X_PETICION) REFERENCES PF_PETICIONES (X_PETICION);	
	
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.X_ID_TRANSACCION  		IS 'Clave primaria';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.C_CREADO             	IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.F_CREADO              	IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.C_MODIFICADO         	IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.F_MODIFICADO          	IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.D_ESTADO  	        	IS 'Estado de la solicitud (N: Alta, P: Pendiente, A: Anulada, F: Firmada, R: Rechazada)';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.D_DESCRIPCION  	    	IS 'Descripción de la solicitud';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.D_PRIORIDAD   	    	IS 'Prioridad de la solicitud (N: Normal, A: Alta)';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.D_FORMATO_FIRMA     	IS 'Formato de firma (CADES, XADES, PADES)';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.D_VERSION_XADES         IS 'Versión de firma XADES (1.2.2, 1.3.2)';	
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.D_TIPO_MULTIFIRMA       IS 'Tipo de multifirma (NO, SERIE, PARALELO)';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.F_FECHA_LIMITE    		IS 'Fecha límite de la solicitud (Solo informativa)';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.D_REMITENTE    	        IS 'Nombre y apellidos del remitente';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.SOLICITUD_X_GESTOR      IS 'Identificador del sistema de gestión que envió la solicitud';
COMMENT ON COLUMN PF_DOCELWEB_SOLICITUD_SPFIRMA.SOLICITUD_X_PETICION    IS 'Identificador de la petición asociada a la solicitud una vez registrada';

CREATE SEQUENCE PF_S_DOCELWEB_SOL_SPFIR
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

-- TABLA PF_DOCELWEB_LISTA_FIRMANTES

CREATE TABLE PF_DOCELWEB_X_LISTA_FIRMANTES
    (
        X_ID_TRANSACCION NUMBER(10) NOT NULL,
        X_USUARIO NUMBER(10) NOT NULL        
    )
TABLESPACE TPFIRMAMGHIST;    

ALTER TABLE PF_DOCELWEB_X_LISTA_FIRMANTES ADD CONSTRAINT PF_DOCELWEB_X_LIST_FIR_PK 
    PRIMARY KEY (X_ID_TRANSACCION, X_USUARIO) USING INDEX TABLESPACE IPFIRMAMGHIST;
ALTER TABLE PF_DOCELWEB_X_LISTA_FIRMANTES ADD CONSTRAINT PF_DOCELWEB_X_REQ_FK
	FOREIGN KEY (X_ID_TRANSACCION) REFERENCES PF_DOCELWEB_SOLICITUD_SPFIRMA (X_ID_TRANSACCION);    
ALTER TABLE PF_DOCELWEB_X_LISTA_FIRMANTES ADD CONSTRAINT PF_DOCELWEB_X_FIR_FK
	FOREIGN KEY (X_USUARIO) REFERENCES PF_USUARIOS (X_USUARIO);	
	
COMMENT ON COLUMN PF_DOCELWEB_X_LISTA_FIRMANTES.X_ID_TRANSACCION  	IS 'Clave primaria, Clave ajena hacia PF_DOCELWEB_SOLICITUD_SPFIRMA';
COMMENT ON COLUMN PF_DOCELWEB_X_LISTA_FIRMANTES.X_USUARIO  			IS 'Clave primaria, Clave ajena hacia PF_USUARIOS';

-- TABLA PF_DOCELWEB_DOCUMENTO

CREATE TABLE PF_DOCELWEB_DOCUMENTO
    (
        X_DOCUMENTO NUMBER(10) NOT NULL,
        C_CREADO VARCHAR2(20) NOT NULL,
        F_CREADO DATE DEFAULT SYSDATE NOT NULL,
        C_MODIFICADO VARCHAR2(20) NOT NULL,
        F_MODIFICADO DATE DEFAULT SYSDATE NOT NULL,
        D_DESCRIPCION VARCHAR2(255 CHAR) NOT NULL,
        D_RUTA_DOCUMENTO VARCHAR2(255 CHAR) NOT NULL,
        D_TIPO_DOCEL CHAR(1) NOT NULL,
        D_REQ_FIRMA CHAR(1) DEFAULT 'N' NOT NULL,
        D_DISPOSICION_URL VARCHAR2(500 CHAR),
        DOC_X_ARCHIVO NUMBER(10),
        DOC_X_SOLICITUD NUMBER(10) NOT NULL,
        DOC_X_PFDOC NUMBER(10)
    )
TABLESPACE TPFIRMAMGHIST; 
    
ALTER TABLE PF_DOCELWEB_DOCUMENTO ADD CONSTRAINT PF_DOCELWEB_DOCUMENTO_PK 
    PRIMARY KEY (X_DOCUMENTO) USING INDEX TABLESPACE IPFIRMAMGHIST;
ALTER TABLE PF_DOCELWEB_DOCUMENTO ADD CONSTRAINT PF_DOCELWEB_DOC_ARCH_FK 
	FOREIGN KEY (DOC_X_ARCHIVO) REFERENCES PF_ARCHIVOS (X_ARCHIVO);
ALTER TABLE PF_DOCELWEB_DOCUMENTO ADD CONSTRAINT PF_DOCELWEB_DOC_SOL_FK 
	FOREIGN KEY (DOC_X_SOLICITUD) REFERENCES PF_DOCELWEB_SOLICITUD_SPFIRMA (X_ID_TRANSACCION);
ALTER TABLE PF_DOCELWEB_DOCUMENTO ADD CONSTRAINT PF_DOCELWEB_DOC_PFDOC_FK 
	FOREIGN KEY (DOC_X_PFDOC) REFERENCES PF_DOCUMENTOS (X_DOCUMENTO);	

COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.X_DOCUMENTO  		IS 'Clave primaria';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.C_CREADO            IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.F_CREADO            IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.C_MODIFICADO        IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.F_MODIFICADO        IS 'Campo de auditoria';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.D_DESCRIPCION  	    IS 'Descrición del documento';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.D_RUTA_DOCUMENTO  	IS 'Carpetas y nombre del documento';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.D_TIPO_DOCEL  	    IS 'Tipo de documento (E: Documento electrónico, U: Puesta a disposición/URL, P: Documento en papel)';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.D_REQ_FIRMA  	    IS 'Indica si requiere firma (S/N). Obligatorio N para documentos en papel';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.D_DISPOSICION_URL  	IS 'URL de la puesta a disposición';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.DOC_X_ARCHIVO  	    IS 'Contenido del documento almacenado en el gestor documental de portafirmas';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.DOC_X_SOLICITUD   	IS 'Solicitud InterfazGenerica propietaria del documento registrado';
COMMENT ON COLUMN PF_DOCELWEB_DOCUMENTO.DOC_X_PFDOC  	    IS 'Documento de portafirmas relacionado con el documento de InterfazGenerica una vez registrada la petición asociada al mismo';

CREATE SEQUENCE PF_S_DOCELWEB_DOCUMENTO
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;


-- TABLA PF_EMAILS_PETICION
CREATE TABLE PF_EMAILS_PETICION
(
	X_EMAIL_PETICION     NUMBER(10) NOT NULL,    --  Clave primaria 
	C_CREADO             VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_CREADO             DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	C_MODIFICADO         VARCHAR2(20) DEFAULT USER NOT NULL,    --  Campo de auditoria 
	F_MODIFICADO         DATE DEFAULT SYSDATE NOT NULL,    --  Campo de auditoria 
	PET_X_PETICION       NUMBER(10) NOT NULL,    --  Clave ajena a PF_PETICIONES 
	C_EMAIL              VARCHAR2(255 CHAR) NOT NULL    --  Email
)
TABLESPACE  TPFIRMAMGHIST
;

COMMENT ON COLUMN PF_EMAILS_PETICION.X_EMAIL_PETICION  IS 'Clave primaria'
;
COMMENT ON COLUMN PF_EMAILS_PETICION.C_CREADO            IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_EMAILS_PETICION.F_CREADO            IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_EMAILS_PETICION.C_MODIFICADO        IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_EMAILS_PETICION.F_MODIFICADO        IS 'Campo de auditoria'
;
COMMENT ON COLUMN PF_EMAILS_PETICION.PET_X_PETICION       IS 'Clave ajena a PF_PETICIONES'
;
COMMENT ON COLUMN PF_EMAILS_PETICION.C_EMAIL     IS 'Email de notificacion'
;

-- Primary Key
ALTER TABLE PF_EMAILS_PETICION ADD CONSTRAINT PF_EMA_PET_PK 
	PRIMARY KEY (X_EMAIL_PETICION) USING INDEX TABLESPACE IPFIRMAMGHIST
;

-- Foreign Keys
ALTER TABLE PF_EMAILS_PETICION ADD CONSTRAINT PF_EMA_PET_PET_FK
  FOREIGN KEY (PET_X_PETICION) REFERENCES PF_PETICIONES(X_PETICION);
  
-- Se crean los índices
CREATE INDEX PF_I_EMA_PET_PET_FK ON PF_EMAILS_PETICION(PET_X_PETICION ASC)
TABLESPACE  IPFIRMAMGHIST;

ALTER TABLE PF_ETIQUETAS_PETICION 
ADD (GRO_X_GROUP NUMBER(10) );

ALTER TABLE PF_DOCUMENTOS 
ADD (USU_X_USUARIO_ANEXA NUMBER(10) );

CREATE TABLE PF_USUARIOS_DOC_VISIBLES 
(
  USU_X_USUARIO NUMBER(10) NOT NULL 
, DOC_X_DOCUMENTO NUMBER(10) NOT NULL 
, CONSTRAINT PF_USUARIOS_DOC_VISIBLES_PK PRIMARY KEY 
  (
    USU_X_USUARIO 
  , DOC_X_DOCUMENTO 
  )
  ENABLE 
);

ALTER TABLE PF_APLICACIONES 
ADD (VISIBLE_EN_PORTAFIRMA_WEB NUMBER DEFAULT 0 NOT NULL);

ALTER TABLE PF_APLICACIONES 
ADD (DESCRIPCION_WEB VARCHAR2(50 CHAR) );

CREATE TABLE
    PF_USUARIOS_COMENTARIO
    (
        X_USUARIO_COMENTARIO NUMBER(10) NOT NULL,
        C_CREADO VARCHAR2(20 CHAR) DEFAULT 'USER ' NOT NULL,
        F_CREADO DATE DEFAULT SYSDATE NOT NULL,
        C_MODIFICADO VARCHAR2(20 CHAR) DEFAULT 'USER ' NOT NULL,
        F_MODIFICADO DATE DEFAULT SYSDATE NOT NULL,
        COM_X_COMENTARIO NUMBER(10) NOT NULL,
        USU_X_USUARIO NUMBER(10) NOT NULL,
        CONSTRAINT PF_UCOM_PK PRIMARY KEY (X_USUARIO_COMENTARIO),
        CONSTRAINT PF_UCOM_COM_FK FOREIGN KEY (COM_X_COMENTARIO) REFERENCES PF_COMENTARIOS
        (X_COMENTARIO),
        CONSTRAINT PF_UCOM_USU_FK FOREIGN KEY (USU_X_USUARIO) REFERENCES PF_USUARIOS (X_USUARIO)
    );
